### PR TITLE
Ask config values as needed

### LINKED ISSUE #3: Though about config after #2
Right now produce asks everything it needs before running app. Also on #2 we added if wrap to check if we're skipping iTC, though I found it very ugly. What do you think if we ask for config only we actually need, and still provide initial values.

We could do this by modifying [`Config.val`](https://github.com/KrauseFx/produce/blob/master/lib/produce/config.rb#L39-L42) to return value or given key if config has it, and if doesn't have then ask user.

This eliminates need to ask all settings beforehand and we don't need to guess which configs we need to ask/not ask. Also users will be able to fully automate using initial values still.

Let me know if you want me to show you code for this. (to make my suggestions clear)

### PR DESCRIPTION
**Pull request by almassapargali**
Resolves #3, looking forward to any feedback!

### CODE REVIEW

**Comment by almassapargali** [comment]
Also now we can create config from hash, which may be useful when using with fastline, etc.

**Comment by KrauseFx** [comment]
Looks great, thanks for working on this :+1:

**Comment by almassapargali** [comment]
I'm sorry. It stumbled me outside that this pr has bug. It modifies primary
language when validating, but still uses original one.

**Comment by almassapargali** [comment]
Thanks for merging! I'll send hotfix shortly.

**Comment by KrauseFx** [comment]
Cool, thanks :+1:

**Pull request merged**
